#include<iostream>
#include "LinkedList.h"
#include "myLinkedList.h"
using namespace std;
//FOLLOWING THE THE MEHOD I USED TO SOLVE THIS PROBLEM!
/*STEP 1: UNDERSTANDING THE TASK
IN THIS TASK, I UNDERSTOOD THAT WE ARE WORKING WITH A LINKED LIST.A LINKED LIST IS A STRUCTURE WHERE DATA IS STORED IN NODES AND EACH NODE IS CONNECTED WITH THE NEXT ONE LIKE A CHAIN.EACH NODE HAS TWO PARTS : DATA AND A POINTER TO THE NEXT NODE.
THE MAIN REQUIREMENT OF THIS TASK IS TO FIX THE DESTRUCTOR AND IMPLEMENT THE COPY CONSTRUCTOR.THE GIVEN DESTRUCTOR WAS NOT CORRECT BECAUSE IT WAS ONLY DELETING THE FIRST AND LAST NODE, NOT THE COMPLETE LIST.THIS CAN CAUSE MEMORY LEAK.
ALSO, THE COPY CONSTRUCTOR WAS MISSING, SO WE NEEDED TO CREATE ONE THAT MAKES A PROPER COPY OF THE LINKED LIST(NOT JUST COPYING ADDRESSES BUT CREATING NEW NODES).
STEP 2: SOLUTION APPROACH
FOR DESTRUCTOR :
IF THE LINKED LIST IS :
A ? B ? C ? D
WE WILL DELETE NODES ONE BY ONE :
FIRST DELETE A, THEN MOVE TO B, DELETE B, THEN C, THEN D UNTIL LIST BECOMES EMPTY.
WE USED A TEMP POINTER WHICH STARTS FROM FIRST NODE AND MOVES FORWARD WHILE DELETING EACH NODE.
FOR COPY CONSTRUCTOR :
IF ORIGINAL LIST IS :
A ? B ? C
WE CREATE A NEW EMPTY LIST AND COPY VALUES ONE BY ONE :
INSERT A ? INSERT B ? INSERT C
SO NEW LIST BECOMES :
A ? B ? C
THIS IS CALLED DEEP COPY BECAUSE NEW MEMORY IS CREATED FOR EACH NODE.
STEP 3 : FUNCTIONS USED
WE REUSED insertAtLast() FUNCTION.
REASON :
    INSTEAD OF WRITING NEW LOGIC FOR ADDING NODES, WE USED THE ALREADY AVAILABLE FUNCTION TO INSERT VALUES AT THE END OF THE NEW LIST.
    WORKING EXAMPLE :
ORIGINAL LIST : 10 ? 20 ? 30
COPY PROCESS :
INSERT 10 ? INSERT 20 ? INSERT 30
NEW LIST : 10 ? 20 ? 30
IF WE REMOVE A VALUE FROM ORIGINAL LIST :
ORIGINAL: 10 ? 20
COPIED : 10 ? 20 ? 30
THIS SHOWS BOTH LISTS ARE SEPARATE.
STEP 4 : LEARNING
FROM THIS TASK, I LEARNED HOW IMPORTANT IT IS TO HANDLE MEMORY PROPERLY IN LINKED LIST.I ALSO LEARNED THAT IF DESTRUCTOR IS NOT WRITTEN CORRECTLY, IT CAN CAUSE MEMORY LEAK.
I ALSO UNDERSTOOD THE DIFFERENCE BETWEEN SHALLOW COPY AND DEEP COPY.COPY CONSTRUCTOR HELPS IN MAKING A SAFE AND INDEPENDENT COPY OF A DATA STRUCTURE.
STEP 5: SKILLS DEVELOPED
AFTER COMPLETING THIS TASK, I CAN :
*WRITE A CORRECT DESTRUCTOR FOR LINKED LIST
* IMPLEMENT A COPY CONSTRUCTOR
* HANDLE POINTERS MORE CONFIDENTLY
* SOLVE MEMORY RELATED PROBLEMS
NOW I CAN APPLY THESE CONCEPTS TO OTHER STRUCTURES LIKE STACK AND QUEUE AS WELL. */

int main()
{
    myLinkedList list1;

    list1.insertAtLast(10);
    list1.insertAtLast(20);
    list1.insertAtLast(30);

    cout << "Original List:\n";
    list1.display();

     //Test Copy Constructor
    myLinkedList list2 = list1;

    cout << "Copied List:\n";
    list2.display();

    // Modify original to check deep copy
    list1.removeFromLast();

    cout << "After removing from original:\n";
    cout << "Original List:\n";
    list1.display();

    cout << "Copied List (should remain same):\n";
    list2.display();

    return 0;
}
